# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8135fc093c9c3c3438112e2d74e3930e48c6080e8c3e3b66b5aafe768dbdf56293f17dd456ad9a8d3a29e50489281cb2e0a2f3da28965748350c997f9dcd1b3b

test:
  secret_key_base: fc1fddefede410c3624de29a0da3610655ae40a6adb4caa56fc88183a635b4a2e8819b28501f21f6f226d91d1ad0b0273c4283c537c95cb69f0a91818de50e50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
